---
- name: Create mysql database
  mysql_db: 
    name: "{{ mysql_db_name }}"
    state: present

- name: Create mysql user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL"